// ─── Attendance Types ─────────────────────────────────────────────────────────
// Business rule:
//   PRESENT            → isBillable = true
//   ABSENT_UNEXCUSED   → isBillable = true  (no approved leave)
//   ABSENT_EXCUSED     → isBillable = false (approved leave → not charged)
//   LATE               → isBillable = true

export type AttendanceStatus = "PRESENT" | "ABSENT_EXCUSED" | "ABSENT_UNEXCUSED" | "LATE";

export interface AttendanceRecord {
    id: string;
    sessionId: string;
    classId: string;
    className: string;
    date: string;       // "YYYY-MM-DD"
    sessionTime: string;
    status: AttendanceStatus;
    /** Whether this session is charged in the bill */
    isBillable: boolean;
    checkedInAt?: string; // ISO timestamp when QR was scanned
    note?: string;
}

export interface CheckInPayload {
    /** QR code content generated by Teacher's attendance screen */
    qrCode: string;
    sessionId: string;
}

export interface AttendanceSummary {
    classId: string;
    className: string;
    totalSessions: number;
    present: number;
    absentExcused: number;     // Not billed
    absentUnexcused: number;   // Still billed
    late: number;
    attendanceRate: number;    // percentage
}

export const ATTENDANCE_STATUS_LABELS: Record<AttendanceStatus, string> = {
    PRESENT: "Có mặt",
    ABSENT_EXCUSED: "Nghỉ có phép",
    ABSENT_UNEXCUSED: "Nghỉ không phép",
    LATE: "Đi muộn",
};
