export {
    examKeys,
    useTeacherExams,
    useExamDetail,
    useExamStats,
    useCreateExam,
    useUpdateExam,
    useDeleteExam,
    useArchiveExam,
    useExamInfo,
    useExamStatistics,
    useStudentResults,
    useQuestionAnalysis,
    useStudentExamResult,
} from "./useExam";
